import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import FooterPage from "../components/Footer/footer";
import HeaderPage from "../components/Header/page";
import NavPage from "../components/Nav/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderPage />
        <NavPage />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
